rgbd:
    max_shape: [null, 480, 640, 4]
    chunk_shape: [1, 480, 640, 4]

dof_values:
    max_shape: [null, 3]
    chunk_shape: [1, 3]

palm_pose:
    max_shape: [null, 7]
    chunk_shape: [1, 7]

joint_values:
    max_shape: [null, 8]
    chunk_shape: [1, 8]

uvd:
    max_shape: [null, 4, 3]
    chunk_shape: [1, 4, 3]

wrist_roll:
    max_shape: [null, 1]
    chunk_shape: [1, 1]

virtual_contacts:
    max_shape: [null, 4 , 3]
    chunk_shape: [1, 4, 3]

model_name:
    dtype: String
    max_shape: [null, 1]
    chunk_shape: [1, 1]

energy:
    max_shape: [null, 1]
    chunk_shape: [1, 1]

grasp_type:
    max_shape: [null, 1]
    chunk_shape: [1, 1]